"""Genre Model Added

Revision ID: 975f8758c86d
Revises: de005612806a
Create Date: 2020-09-04 09:26:08.737000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '975f8758c86d'
down_revision = 'de005612806a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Genre',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Genre')
    # ### end Alembic commands ###
